### PR TITLE
Support linkmap generation feature

### PR DESCRIPTION
**Pull request by FaBrand**

### CODE REVIEW

**Comment by hexdae** [comment]
This is just incredibly cool. Mind if I add a small example?

**Review by hexdae — APPROVED** [review]

**Comment by hexdae** [comment]
Ok, this is ready to be merged, I'll go ahead and do that by end of day. Let me know if you're ok with it and if you need this release to the bazel registry ASAP

**Comment by FaBrand** [comment]
Lgtm. Will double check the test cases shortly

**Review by FaBrand — COMMENTED** [review]
LGTM @hexdae Thank you for the quick response :)

**Comment by hexdae** [comment]
Released on bazel registry https://github.com/bazelbuild/bazel-central-registry/pull/2288

**Pull request merged**
